version: '3.8'
services:
  temurin-service:
    build:
      dockerfile: jar/Dockerfile_jar
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/demo
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.flyway.enabled=false #Disabled just to compare startup with native-service
  graalvm-native-service:
    build:
      dockerfile: native-image/Dockerfile_native
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/demo
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.datasource.driver-class-name=org.postgresql.Driver
  graalvm-jit-service:
    build:
      dockerfile: graalvm-jit/Dockerfile_jit
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/demo
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.datasource.driver-class-name=org.postgresql.Driver
  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    volumes:
      - psql_data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  psql_data:
    name: postgresql_postgresql-data