FROM ghcr.io/graalvm/graalvm-ce:ol9-java17-22.3.1

ENV M2_HOME=/opt/maven
ENV PATH="${M2_HOME}/bin:${PATH}"

RUN microdnf install -y unzip zip
RUN curl "https://downloads.apache.org/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.zip" -s -o "mvn.zip" \
    && unzip mvn.zip \
    && mv apache-maven-3.9.1/ /opt/maven/ \
    && rm mvn.zip
RUN /bin/gu install native-image

COPY .. /home/user/spring-graalvm-service
WORKDIR /home/user/spring-graalvm-service

ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]